###### Problem Statement 1:
###### Write a function so that the columns of the output matrix are powers of the input vector.
###### The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [7]:
class AlexandreTheophileVandermonde:
    def generateVandermondeMatrix(self,vector,power,isPowerIncreasing):
        vSize=vector.size
        finalMatrix=np.empty((power,vSize),dtype=int)
    
        if isPowerIncreasing.upper()=="TRUE":
            for i in range(power):
                power_vector=np.array(np.power(vector,i))
                finalMatrix[i]=power_vector
        else:
            for i in range(power-1,-1,-1):
                power_vector=np.array(np.power(vector,i))
                finalMatrix[(power-1)-i]=power_vector
        return finalMatrix

In [10]:
import numpy as np
class Test:
    obj = AlexandreTheophileVandermonde()
    print('********Create matrix with a geometric progression*********')

    vector=input('Enter vector element sepated by comma eg. 1,2,3 : ' )

    power=int(input('Enter the power (N) on input vector : '))

    inputList=[int(x) for x in vector.split(',')]

    print('Input value list is :')
    print(inputList)

    vector=np.array(inputList)
    print('Input vector is :')
    print(vector)

    isPowerIncreasing=input("Enter True or False for  increasing order of powers: ")

    result_array=obj.generateVandermondeMatrix(vector,power,isPowerIncreasing)
    print('Vandermonde matrix:')
    print(result_array.T)


********Create matrix with a geometric progression*********
Enter vector element sepated by comma eg. 1,2,3 : 1,2,3,4
Enter the power (N) on input vector : 4
Input value list is :
[1, 2, 3, 4]
Input vector is :
[1 2 3 4]
Enter True or False for  increasing order of powers: true
Vandermonde matrix:
[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]]
